[default.extend-words]
# Neovim plugin names
noice = "noice"
Noice = "Noice"
# External schema identifiers
Parm = "Parm"
# Nixvim directives
annote = "annote"
# Keymaps
fo = "fo"
aso = "aso"
ues = "ues"
ue = "ue"
ges = "ges"
aas = "aas"
# Vim commands
enew = "enew"
iput = "iput"
