[book]
authors = ["gmarler"]
language = "en"
src = "."
title = "gmarlervim Docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/gmarler/my-nixvim"
site-url = "/"
